# Site settings
title: LoganMakesGames
email:  
description: > # keep this and put description below
  
url: "https://loganmakesgames.github.io" # the base hostname & protocol for your site
linkedin_url: 
github_username: 
twitter_username: 
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
